#!/bin/bash

# command aliases
## vim simulation
if [ -n "$OS_UNIX" ];then
    alias ls="ls -G -F"
else
    alias ls="ls -F --color=always"
fi
if [ -n "$OS_MAC" ];then
	alias vim="mac_clipboard_reattach `which vim`"
fi

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls -F'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias '..'='cd ..'
alias '....'='cd ../..'
alias ':e'=vim
alias ':q'=exit
alias 'gbk2utf8'='iconv -fgbk -tutf8'
alias 'gentag'='ctags -R --c++-kinds=+px --fields=+iaS --extra=+q .'
alias 'q'=exit
alias 'x'=exit
alias '~'='cd ~'
alias c='clyde'
alias cls=clear
alias df='df -h'
alias du='du -h'
alias echoe='echo -e'
alias f=finger
alias g2u=gbk2utf8
alias g=git
alias hex='od -Ax -tx1z -v'
alias irc='weechat'
alias k='kubectl'
alias kb='kustomize build --enable-helm --load-restrictor=LoadRestrictionsNone'
alias ktl='kubectl'
alias less='less -R'
alias ll='ls -alh'
alias lla='lsa -l'
alias llh='ls -lh'
alias lsa='ls -ahF'
alias lsal='lsa -l'
alias lsl='ls -lhF'
alias lsla='lsal'
alias lsls="lsl -S"
alias man='LC_ALL=C LANG=C man'
alias mutt="COLORFGBG='15;color233' mutt"
alias rot13="tr a-zA-Z n-za-mN-ZA-M"
alias slrn="slrn -n"
alias y=yaourt
alias t=tmux
